name = "Gagecraft NEO"
author = "JWazowski et al"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a47ecdcf007bae5d613434965cddb05b1ce05bc114f0fdb699d27c4e8e69e82"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
