name = "Gagecraft NEO"
author = "JWazowski et al"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72fe3273e00220be2fd40165be9063111b61b959140931446a82805bc097e9f2"

[versions]
fabric = "0.19.5"
minecraft = "26.3"
